/*

*/
var aNavItemData = [
    [
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        }
    ],
    [
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        }
    ],
    [
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        }
    ],
    [
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        }
    ],
    [
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        }
    ],
    [
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        }
    ],
    [
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-41.jpg',
        	name:'坚果R1',
        	price:'3299'
        },
        {
            url:'http://www.taobao.com',
        	img:'img/img-lt/lt-40.jpg',
        	name:'坚果R1',
        	price:'3299'
        }
    ],
];